import Header from '@/components/Header'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { ArrowRight, Microscope, TrendingUp, Users, Target, BarChart3, Eye, Zap, Brain, Atom, Building2, User, Mail, Phone, MapPin, Send, CheckCircle } from 'lucide-react'
import Link from 'next/link'

export default function LifeSciencesPage() {
  console.log("Life Sciences page loaded")

  return (
    <div className="min-h-screen bg-white">
      <Header />
      
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-proof-blue-50 to-proof-purple-50 py-24">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="flex items-center mb-6">
                <Microscope className="h-8 w-8 text-proof-blue-600 mr-3" />
                <span className="text-proof-blue-600 font-semibold text-lg">Life Sciences</span>
              </div>
              <h1 className="text-5xl font-bold text-proof-gray-900 mb-6">
                Navigate the $5T Biotech Revolution
              </h1>
              <p className="text-xl text-proof-gray-600 mb-8 leading-relaxed">
                Transform your life sciences business with strategic insights into AI-driven drug discovery, gene therapy commercialization, and precision medicine adoption. We help biotech and pharmaceutical companies understand the market dynamics in the fastest-growing healthcare sector.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Button className="bg-proof-blue-600 hover:bg-proof-blue-700 text-white px-8 py-3 text-lg font-semibold" asChild>
                  <Link href="/contact">
                    Schedule Research Consultation
                  </Link>
                </Button>
                <Button variant="outline" className="border-proof-blue-600 text-proof-blue-600 hover:bg-proof-blue-50 px-8 py-3 text-lg font-semibold">
                  View Case Studies
                </Button>
              </div>
            </div>
            <div className="relative">
              <div className="bg-gradient-to-br from-proof-blue-100 to-proof-purple-100 rounded-2xl p-8 shadow-lg">
                <img 
                  src="https://images.unsplash.com/photo-1559757175-0c7e6ad014e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80" 
                  alt="Life sciences laboratory and research" 
                  className="w-full h-80 object-cover rounded-lg shadow-md"
                />
                <div className="absolute -bottom-4 -right-4 bg-white p-4 rounded-lg shadow-lg">
                  <div className="flex items-center space-x-3">
                    <TrendingUp className="h-6 w-6 text-proof-green-600" />
                    <div>
                      <div className="text-sm font-semibold text-proof-gray-900">Market Growth</div>
                      <div className="text-xs text-proof-gray-600">$5T by 2034</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Market Update Section */}
      <section className="py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-proof-gray-900 mb-6">2024-2025 Market Intelligence</h2>
            <p className="text-xl text-proof-gray-600 max-w-3xl mx-auto">
              Revolutionary developments transforming the life sciences industry and their impact on market opportunities.
            </p>
          </div>
          
          <div className="grid lg:grid-cols-3 gap-8 mb-12">
            <Card className="p-6 bg-gradient-to-br from-blue-50 to-purple-50 border-0">
              <Brain className="h-10 w-10 text-blue-600 mb-4" />
              <h3 className="text-lg font-semibold text-proof-gray-900 mb-3">AI-Generated Drug Candidates</h3>
              <p className="text-proof-gray-600 text-sm mb-3">
                Up to <strong>30% of new drug candidates expected to be AI-generated by end of 2025</strong>, dramatically accelerating discovery timelines and reducing costs.
              </p>
              <div className="text-xs text-blue-600 font-medium">Impact: Revolutionary</div>
            </Card>
            
            <Card className="p-6 bg-gradient-to-br from-purple-50 to-pink-50 border-0">
              <Atom className="h-10 w-10 text-purple-600 mb-4" />
              <h3 className="text-lg font-semibold text-proof-gray-900 mb-3">Gene Therapy Momentum</h3>
              <p className="text-proof-gray-600 text-sm mb-3">
                Commercial momentum following CRISPR-based therapy approvals, with more novel gene therapies reaching market for rare and genetic diseases.
              </p>
              <div className="text-xs text-purple-600 font-medium">Trend: Accelerating</div>
            </Card>
            
            <Card className="p-6 bg-gradient-to-br from-green-50 to-blue-50 border-0">
              <Target className="h-10 w-10 text-green-600 mb-4" />
              <h3 className="text-lg font-semibold text-proof-gray-900 mb-3">Precision Medicine Growth</h3>
              <p className="text-proof-gray-600 text-sm mb-3">
                Targeted therapies, individualized cancer vaccines, and antibody-drug conjugates driving growth in oncology and metabolic diseases.
              </p>
              <div className="text-xs text-green-600 font-medium">Opportunity: Massive</div>
            </Card>
          </div>

          <Card className="p-8 bg-gradient-to-r from-proof-blue-600 to-proof-purple-600 text-white">
            <div className="grid lg:grid-cols-2 gap-8 items-center">
              <div>
                <h3 className="text-2xl font-bold mb-4">Capital and M&A Dynamics</h3>
                <p className="text-blue-100 mb-6">
                  Only 40% of US-listed biotechs have sufficient cash through 2025, creating consolidation opportunities. Large pharma is increasingly active in M&A with favorable regulatory environment.
                </p>
                <div className="flex items-center text-blue-100">
                  <Microscope className="h-5 w-5 mr-2" />
                  <span className="text-sm">PROOF provides strategic intelligence for investment and acquisition decisions</span>
                </div>
              </div>
              <div className="text-center">
                <div className="text-4xl font-bold mb-2">$3T</div>
                <div className="text-blue-100">Pharmaceutical market by 2034</div>
              </div>
            </div>
          </Card>
        </div>
      </section>

      {/* Client Logos Section */}
      <section className="py-20 bg-proof-gray-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-proof-gray-900 mb-6">Trusted by Leading Life Sciences Companies</h2>
            <p className="text-xl text-proof-gray-600 max-w-3xl mx-auto">
              We partner with innovative biotech, pharmaceutical, and life sciences companies driving breakthrough therapies.
            </p>
          </div>
          
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-8 items-center">
            <div className="bg-white p-6 rounded-lg shadow-sm flex items-center justify-center h-20">
              <div className="text-lg font-bold text-proof-gray-700">BioPharma</div>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm flex items-center justify-center h-20">
              <div className="text-lg font-bold text-proof-gray-700">GeneTherapy</div>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm flex items-center justify-center h-20">
              <div className="text-lg font-bold text-proof-gray-700">PrecisionMed</div>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm flex items-center justify-center h-20">
              <div className="text-lg font-bold text-proof-gray-700">BioTech Pro</div>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm flex items-center justify-center h-20">
              <div className="text-lg font-bold text-proof-gray-700">DrugDev</div>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-sm flex items-center justify-center h-20">
              <div className="text-lg font-bold text-proof-gray-700">Therapeutic</div>
            </div>
          </div>
          
          <div className="text-center mt-12">
            <p className="text-proof-gray-600 italic">
              "PROOF's market intelligence helped us navigate gene therapy commercialization and achieve successful launch in 12 months"
            </p>
            <p className="text-sm text-proof-gray-500 mt-2">— Chief Commercial Officer, Leading Biotech Company</p>
          </div>
        </div>
      </section>

      {/* Research Solutions Section */}
      <section className="py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-proof-gray-900 mb-6">Research Solutions for Life Sciences</h2>
            <p className="text-xl text-proof-gray-600 max-w-3xl mx-auto">
              Specialized research methodologies to help life sciences companies navigate complex markets and accelerate innovation.
            </p>
          </div>
          
          <div className="grid lg:grid-cols-2 gap-8 mb-12">
            <Card className="p-8 bg-white">
              <Users className="h-10 w-10 text-proof-blue-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Drug Development Strategy</h3>
              <p className="text-proof-gray-600 mb-6">
                Optimize your drug development pipeline with insights into therapeutic areas, target populations, and competitive landscapes.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2 mb-6">
                <li>• Therapeutic area prioritization</li>
                <li>• Target indication validation</li>
                <li>• Competitive intelligence</li>
                <li>• Development pathway optimization</li>
              </ul>
              <div className="flex items-center text-proof-blue-600 text-sm font-medium">
                Learn More <ArrowRight className="ml-2 h-4 w-4" />
              </div>
            </Card>
            
            <Card className="p-8 bg-white">
              <Target className="h-10 w-10 text-proof-purple-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Market Access & Pricing</h3>
              <p className="text-proof-gray-600 mb-6">
                Navigate complex pricing and reimbursement landscapes for successful therapy commercialization.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2 mb-6">
                <li>• Payer value proposition development</li>
                <li>• Health economics modeling</li>
                <li>• Pricing strategy optimization</li>
                <li>• Reimbursement pathway analysis</li>
              </ul>
              <div className="flex items-center text-proof-purple-600 text-sm font-medium">
                Learn More <ArrowRight className="ml-2 h-4 w-4" />
              </div>
            </Card>
            
            <Card className="p-8 bg-white">
              <BarChart3 className="h-10 w-10 text-proof-blue-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Gene Therapy Commercialization</h3>
              <p className="text-proof-gray-600 mb-6">
                Understand physician and patient readiness for novel gene therapies and optimize launch strategies.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2 mb-6">
                <li>• Physician adoption barriers</li>
                <li>• Patient journey mapping</li>
                <li>• Treatment center capabilities</li>
                <li>• Launch sequence optimization</li>
              </ul>
              <div className="flex items-center text-proof-blue-600 text-sm font-medium">
                Learn More <ArrowRight className="ml-2 h-4 w-4" />
              </div>
            </Card>
            
            <Card className="p-8 bg-white">
              <Eye className="h-10 w-10 text-proof-purple-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Precision Medicine Adoption</h3>
              <p className="text-proof-gray-600 mb-6">
                Research physician readiness and infrastructure requirements for personalized therapy implementation.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2 mb-6">
                <li>• Biomarker testing adoption</li>
                <li>• Diagnostic pathway analysis</li>
                <li>• Personalization value perception</li>
                <li>• Implementation barrier assessment</li>
              </ul>
              <div className="flex items-center text-proof-purple-600 text-sm font-medium">
                Learn More <ArrowRight className="ml-2 h-4 w-4" />
              </div>
            </Card>
          </div>

          {/* Specialized Research Areas */}
          <div className="bg-white rounded-2xl p-8 shadow-lg">
            <h3 className="text-2xl font-bold text-proof-gray-900 mb-6 text-center">Specialized Research for Life Sciences Innovation</h3>
            <div className="grid md:grid-cols-3 gap-6">
              <div className="text-center">
                <Zap className="h-8 w-8 text-proof-blue-600 mx-auto mb-3" />
                <h4 className="font-semibold text-proof-gray-900 mb-2">AI Drug Discovery</h4>
                <p className="text-sm text-proof-gray-600">Research adoption of AI-powered drug discovery platforms and optimization of AI-human collaboration workflows.</p>
              </div>
              <div className="text-center">
                <Brain className="h-8 w-8 text-proof-purple-600 mx-auto mb-3" />
                <h4 className="font-semibold text-proof-gray-900 mb-2">Regulatory Strategy</h4>
                <p className="text-sm text-proof-gray-600">Navigate complex regulatory pathways for novel therapies and optimize approval strategies.</p>
              </div>
              <div className="text-center">
                <TrendingUp className="h-8 w-8 text-proof-blue-600 mx-auto mb-3" />
                <h4 className="font-semibold text-proof-gray-900 mb-2">Investment & M&A Intelligence</h4>
                <p className="text-sm text-proof-gray-600">Strategic insights for biotech investments, partnerships, and acquisition opportunities.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Case Studies Section */}
      <section className="py-20 bg-proof-gray-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-proof-gray-900 mb-6">Case Studies for Life Sciences</h2>
            <p className="text-xl text-proof-gray-600 max-w-3xl mx-auto">
              Real results from our research with leading biotech companies and pharmaceutical organizations.
            </p>
          </div>
          
          <div className="grid lg:grid-cols-2 gap-8">
            <Card className="p-8 bg-white border-l-4 border-proof-blue-600">
              <div className="flex items-center mb-4">
                <Atom className="h-8 w-8 text-proof-blue-600 mr-3" />
                <div>
                  <h3 className="text-xl font-semibold text-proof-gray-900">Gene Therapy Launch</h3>
                  <p className="text-sm text-proof-gray-600">Commercialization Strategy</p>
                </div>
              </div>
              <p className="text-proof-gray-600 mb-6">
                A biotech company needed to understand physician readiness and optimize their launch strategy for a novel CRISPR-based gene therapy.
              </p>
              <div className="space-y-3 mb-6">
                <div className="flex items-center">
                  <CheckCircle className="h-4 w-4 text-proof-green-600 mr-2" />
                  <span className="text-sm text-proof-gray-600">Identified optimal launch sequence across 15 markets</span>
                </div>
                <div className="flex items-center">
                  <CheckCircle className="h-4 w-4 text-proof-green-600 mr-2" />
                  <span className="text-sm text-proof-gray-600">Reduced physician education time by 60%</span>
                </div>
                <div className="flex items-center">
                  <CheckCircle className="h-4 w-4 text-proof-green-600 mr-2" />
                  <span className="text-sm text-proof-gray-600">Achieved successful launch in 12 months</span>
                </div>
              </div>
              <Link href="/resources/case-studies" className="flex items-center text-proof-blue-600 text-sm font-medium">
                Read Full Case Study <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Card>
            
            <Card className="p-8 bg-white border-l-4 border-proof-purple-600">
              <div className="flex items-center mb-4">
                <Microscope className="h-8 w-8 text-proof-purple-600 mr-3" />
                <div>
                  <h3 className="text-xl font-semibold text-proof-gray-900">Precision Medicine Platform</h3>
                  <p className="text-sm text-proof-gray-600">Market Access Strategy</p>
                </div>
              </div>
              <p className="text-proof-gray-600 mb-6">
                A pharmaceutical company wanted to optimize market access for their personalized cancer therapy platform across multiple oncology indications.
              </p>
              <div className="space-y-3 mb-6">
                <div className="flex items-center">
                  <CheckCircle className="h-4 w-4 text-proof-green-600 mr-2" />
                  <span className="text-sm text-proof-gray-600">Secured reimbursement in 8 key markets</span>
                </div>
                <div className="flex items-center">
                  <CheckCircle className="h-4 w-4 text-proof-green-600 mr-2" />
                  <span className="text-sm text-proof-gray-600">Optimized value proposition for 3 indications</span>
                </div>
                <div className="flex items-center">
                  <CheckCircle className="h-4 w-4 text-proof-green-600 mr-2" />
                  <span className="text-sm text-proof-gray-600">Achieved 85% physician adoption rate</span>
                </div>
              </div>
              <Link href="/resources/case-studies" className="flex items-center text-proof-purple-600 text-sm font-medium">
                Read Full Case Study <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Card>
          </div>
        </div>
      </section>

      {/* Who We Work With Section */}
      <section className="py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-proof-gray-900 mb-6">Who We Work With in Life Sciences</h2>
            <p className="text-xl text-proof-gray-600 max-w-3xl mx-auto">
              From global pharmaceutical giants to innovative biotech startups, we partner with organizations across the life sciences ecosystem.
            </p>
          </div>
          
          <div className="grid lg:grid-cols-3 gap-8 mb-12">
            <Card className="p-8 bg-white">
              <Building2 className="h-10 w-10 text-proof-blue-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Pharmaceutical Companies</h3>
              <p className="text-proof-gray-600 mb-6">
                Global and specialty pharma companies developing innovative therapies and expanding market access.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2">
                <li>• Large pharmaceutical companies</li>
                <li>• Specialty pharma organizations</li>
                <li>• Generic drug manufacturers</li>
                <li>• Contract research organizations</li>
              </ul>
            </Card>
            
            <Card className="p-8 bg-white">
              <Atom className="h-10 w-10 text-proof-purple-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Biotech Innovators</h3>
              <p className="text-proof-gray-600 mb-6">
                Cutting-edge biotech companies developing gene therapies, precision medicines, and novel therapeutic modalities.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2">
                <li>• Gene therapy companies</li>
                <li>• Cell therapy developers</li>
                <li>• Precision medicine startups</li>
                <li>• AI drug discovery platforms</li>
              </ul>
            </Card>
            
            <Card className="p-8 bg-white">
              <Microscope className="h-10 w-10 text-proof-blue-600 mb-4" />
              <h3 className="text-xl font-semibold text-proof-gray-900 mb-4">Diagnostics & Tools</h3>
              <p className="text-proof-gray-600 mb-6">
                Companies developing diagnostic tools, biomarkers, and enabling technologies for personalized medicine.
              </p>
              <ul className="text-sm text-proof-gray-600 space-y-2">
                <li>• Diagnostic device manufacturers</li>
                <li>• Biomarker development companies</li>
                <li>• Laboratory service providers</li>
                <li>• Research tool companies</li>
              </ul>
            </Card>
          </div>

          <Card className="p-8 bg-gradient-to-r from-proof-blue-600 to-proof-purple-600 text-white">
            <div className="text-center">
              <h3 className="text-2xl font-bold mb-4">Who Typically Orders Our Research</h3>
              <div className="grid md:grid-cols-4 gap-6 mt-8">
                <div className="text-center">
                  <Users className="h-8 w-8 mx-auto mb-3 text-blue-100" />
                  <h4 className="font-semibold mb-2">Chief Commercial Officers</h4>
                  <p className="text-sm text-blue-100">Market access and launch strategy</p>
                </div>
                <div className="text-center">
                  <Target className="h-8 w-8 mx-auto mb-3 text-blue-100" />
                  <h4 className="font-semibold mb-2">VP of Strategy</h4>
                  <p className="text-sm text-blue-100">Portfolio planning and development</p>
                </div>
                <div className="text-center">
                  <TrendingUp className="h-8 w-8 mx-auto mb-3 text-blue-100" />
                  <h4 className="font-semibold mb-2">Business Development</h4>
                  <p className="text-sm text-blue-100">Partnership and investment opportunities</p>
                </div>
                <div className="text-center">
                  <BarChart3 className="h-8 w-8 mx-auto mb-3 text-blue-100" />
                  <h4 className="font-semibold mb-2">Market Research</h4>
                  <p className="text-sm text-blue-100">Competitive intelligence and market sizing</p>
                </div>
              </div>
            </div>
          </Card>
        </div>
      </section>

      {/* Why Choose PROOF Section */}
      <section className="py-20 bg-proof-gray-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl font-bold text-proof-gray-900 mb-6">Why Life Sciences Companies Choose PROOF</h2>
              <div className="space-y-6">
                <div className="flex items-start">
                  <div className="w-8 h-8 bg-proof-blue-100 rounded-full flex items-center justify-center mr-4 mt-1">
                    <span className="text-proof-blue-600 font-bold text-sm">1</span>
                  </div>
                  <div>
                    <h3 className="font-semibold text-proof-gray-900 mb-2">Therapeutic Area Expertise</h3>
                    <p className="text-proof-gray-600">Deep understanding of complex therapeutic areas, regulatory pathways, and market access requirements.</p>
                  </div>
                </div>
                <div className="flex items-start">
                  <div className="w-8 h-8 bg-proof-purple-100 rounded-full flex items-center justify-center mr-4 mt-1">
                    <span className="text-proof-purple-600 font-bold text-sm">2</span>
                  </div>
                  <div>
                    <h3 className="font-semibold text-proof-gray-900 mb-2">Innovation Intelligence</h3>
                    <p className="text-proof-gray-600">Specialized research in emerging technologies like AI drug discovery, gene therapy, and precision medicine.</p>
                  </div>
                </div>
                <div className="flex items-start">
                  <div className="w-8 h-8 bg-proof-blue-100 rounded-full flex items-center justify-center mr-4 mt-1">
                    <span className="text-proof-blue-600 font-bold text-sm">3</span>
                  </div>
                  <div>
                    <h3 className="font-semibold text-proof-gray-900 mb-2">Global Market Access</h3>
                    <p className="text-proof-gray-600">Understanding of diverse healthcare systems, regulatory requirements, and reimbursement landscapes worldwide.</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-gradient-to-br from-proof-gray-50 to-proof-blue-50 rounded-2xl p-8">
              <div className="grid grid-cols-2 gap-6 text-center">
                <div>
                  <div className="text-3xl font-bold text-proof-blue-600 mb-2">18+</div>
                  <div className="text-sm text-proof-gray-600">Years in Life Sciences</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-proof-purple-600 mb-2">300+</div>
                  <div className="text-sm text-proof-gray-600">Therapies Analyzed</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-proof-blue-600 mb-2">95%</div>
                  <div className="text-sm text-proof-gray-600">Launch Success Rate</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-proof-purple-600 mb-2">21d</div>
                  <div className="text-sm text-proof-gray-600">Average Study Turnaround</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Form CTA Section */}
      <section className="py-20 bg-gradient-to-br from-proof-blue-600 to-proof-purple-600">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="text-white">
              <h2 className="text-4xl font-bold mb-6">
                Ready to Accelerate Your Life Sciences Innovation?
              </h2>
              <p className="text-xl text-blue-100 mb-8 leading-relaxed">
                Get the strategic insights you need to navigate AI-driven drug discovery, optimize gene therapy commercialization, and succeed in the rapidly evolving life sciences market.
              </p>
              
              <div className="space-y-4 mb-8">
                <div className="flex items-center">
                  <CheckCircle className="h-5 w-5 text-blue-100 mr-3" />
                  <span className="text-blue-100">Free 30-minute consultation on life sciences trends</span>
                </div>
                <div className="flex items-center">
                  <CheckCircle className="h-5 w-5 text-blue-100 mr-3" />
                  <span className="text-blue-100">Custom research proposal within 24 hours</span>
                </div>
                <div className="flex items-center">
                  <CheckCircle className="h-5 w-5 text-blue-100 mr-3" />
                  <span className="text-blue-100">Therapeutic area expertise and market intelligence</span>
                </div>
              </div>
              
              <div className="flex items-start space-x-6">
                <div className="flex items-center">
                  <Phone className="h-5 w-5 text-blue-100 mr-2" />
                  <span className="text-blue-100 text-sm">(555) 123-4567</span>
                </div>
                <div className="flex items-center">
                  <Mail className="h-5 w-5 text-blue-100 mr-2" />
                  <span className="text-blue-100 text-sm">lifesciences@proofinsights.com</span>
                </div>
              </div>
            </div>
            
            <Card className="p-8 bg-white">
              <h3 className="text-2xl font-bold text-proof-gray-900 mb-6">Get Your Life Sciences Research Proposal</h3>
              <form className="space-y-6">
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-proof-gray-700 mb-2">First Name *</label>
                    <input 
                      type="text" 
                      className="w-full px-4 py-3 border border-proof-gray-300 rounded-lg focus:ring-2 focus:ring-proof-blue-500 focus:border-transparent" 
                      placeholder="John"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-proof-gray-700 mb-2">Last Name *</label>
                    <input 
                      type="text" 
                      className="w-full px-4 py-3 border border-proof-gray-300 rounded-lg focus:ring-2 focus:ring-proof-blue-500 focus:border-transparent" 
                      placeholder="Smith"
                      required
                    />
                  </div>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-proof-gray-700 mb-2">Email Address *</label>
                  <input 
                    type="email" 
                    className="w-full px-4 py-3 border border-proof-gray-300 rounded-lg focus:ring-2 focus:ring-proof-blue-500 focus:border-transparent" 
                    placeholder="john.smith@company.com"
                    required
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-proof-gray-700 mb-2">Company Name *</label>
                  <input 
                    type="text" 
                    className="w-full px-4 py-3 border border-proof-gray-300 rounded-lg focus:ring-2 focus:ring-proof-blue-500 focus:border-transparent" 
                    placeholder="Your Life Sciences Company"
                    required
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-proof-gray-700 mb-2">Research Challenge *</label>
                  <textarea 
                    rows={4}
                    className="w-full px-4 py-3 border border-proof-gray-300 rounded-lg focus:ring-2 focus:ring-proof-blue-500 focus:border-transparent" 
                    placeholder="Tell us about your life sciences research needs, drug development challenges, or market access questions..."
                    required
                  />
                </div>
                
                <Button className="w-full bg-proof-blue-600 hover:bg-proof-blue-700 text-white py-3 text-lg font-semibold">
                  <Send className="mr-2 h-5 w-5" />
                  Send Research Proposal Request
                </Button>
              </form>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}